### Data Analysis:

* Data --- Raw input(consisting of impurities)
* Information --- processed data
* Getting the required information by removing unwanted data is called Data Analysis
* For this DataAnalysis we will use 5 libraries:
    * Numpy -- scientific Calculations
    * Pandas -- numerical data as well as the string.Cleaning of data 
    * Scikit Learn -- Machine learning library
    * Matplotlib -- graphical representation
    * Seaborn -- advanced than the matplotlib
* Steps involved in Data Analysis:
    * gathering data
    * cleaning of the data
    * fill those null values or remove those nulls
    * Graphical representation
    * Feeding the data to the ML algorithm
    * Deploy the algorithm to the Machine

### Numpy :

* Numpy --- Numerical Python.
* This is used to perfrom scientific calculations and mathematical operations.
* Numpy library creates all the output in the array format
* We can perform matrix operations using this numpy library.
* The arrays gives us the high efficiency when compared to lists.
* we can create different dimensional arrays using numpy.
*  1 to 32 dimensional arrays can be created using numpy library.
* **Comparision between the numpy array and list:**
    * Array occupies very less space when compared to lists.
    * we cannot perform complex operations on lists where as in arrays we can.
    * Execution time is also very less when compared to lists.
    * vector operations can be performed using arrays.
    * Data can be created in different dimensions.



In [1]:
### importing the numpy library:

import numpy as np


### Creating arrays:

**1-d array**  --- as same as the list
- lists or tuples or any sequences

In [2]:
li = [1,2,3,4,5]
t = (5,6,7,8,9)
a1 = np.array(t)
print(a1)

[5 6 7 8 9]


In [3]:
type(a1)
type(t) ### type of the array

tuple

In [4]:
### elements type

a1.dtype

dtype('int32')

In [5]:
a2 = np.array([1,'a',2,'b'])
a2

array(['1', 'a', '2', 'b'], dtype='<U11')

In [6]:
a3 = np.array([1+2j,2+3j])
a3

array([1.+2.j, 2.+3.j])

In [7]:
a3.dtype

dtype('complex128')

In [8]:
a = np.array([1,2,3,4],dtype = "complex")

In [9]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [10]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.append(a,'a')  ## adding a single element into the array

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'a'],
      dtype='<U11')

In [12]:
np.append(a,['b',10,'c']) ### adding multiple elements into the array.

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'b', '10', 'c'],
      dtype='<U11')

In [13]:
a = np.arange(1,10,2)## start value,end value and step value
a

array([1, 3, 5, 7, 9])

In [14]:
a.nbytes   ### memory occupied by the array

20

In [15]:
a.itemsize  ### memory occupied by each element


4

In [16]:
len(a)  ### Gives the total number of elements

5

In [17]:
### linear spacing: divides the range of into equal parts to get the required elements.The difference between the all 
## consequtive elements is same 

a = np.linspace(1,10,20) ### end value is inclusive
print(a)
b = np.arange(1,10,20)
print(b)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[1]


In [18]:
len(a)

20

In [19]:
## logarithmic spacing:
a = np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [165]:
### full :
np.full(10,"hello")
np.full((2,6,2),98)

array([[[98, 98],
        [98, 98],
        [98, 98],
        [98, 98],
        [98, 98],
        [98, 98]],

       [[98, 98],
        [98, 98],
        [98, 98],
        [98, 98],
        [98, 98],
        [98, 98]]])

In [21]:
### zeros:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [162]:
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
### ones:
import numpy as np
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [166]:
### ndime ---dimension of the array
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**2-d array**:
* more 1-d arrays are called 2-d arrays
* rows and columns will be included in the 2d array

In [25]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
b.ndim

2

In [27]:
b.nbytes

32

In [28]:
b.itemsize

4

In [29]:
len(b)  ### number of rows in the array

2

In [30]:
b.shape  ## gives the number of rows and columns in the array

(2, 4)

In [31]:
b.size ### elements in the array

8

**3-d array:**
* combination of more two 2-d arrays is called 3-d array
* rows,columns as well as 2-d arrays.

In [190]:
c = np.array([[[1,2,3],[5,6,7]],[[2,4,6],[10,12,14]]])
print(c)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 2  4  6]
  [10 12 14]]]


In [191]:
c.ndim

3

In [192]:
c.itemsize

4

In [193]:
c.nbytes

48

In [194]:
c.shape

(2, 2, 3)

In [195]:
len(c)  ### number of 2-d arrays present

2

In [196]:
c.size 

12

**Multi dimensional:**

In [197]:


d = np.array([[1,2,3,4],[2,3,4,5]],ndmin=10)
d

array([[[[[[[[[[1, 2, 3, 4],
               [2, 3, 4, 5]]]]]]]]]])

In [198]:
d.ndim

10

In [199]:
d = np.array([[1,2,3,4],[2,3,4,5]],ndmin = 3)
d

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]]])

### Accessing the elements from the array:

**1-d array**

In [200]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
a[0]

1

In [202]:
a[-1]
a[-4]

7

In [203]:
a[-5:-2]

array([6, 7, 8])

In [204]:
a[:3]

array([1, 2, 3])

**2-d array**

* each row will have the index
* element will also have the index

In [205]:
b

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [206]:
b[1][1]

26

In [207]:
b[1,-1]  ### row index,element index

29

In [208]:
b[:,-1]

array([24, 29])

In [209]:
b[:,-2:]

array([[23, 24],
       [28, 29]])

**3-d array**

In [210]:
c

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 2,  4,  6],
        [10, 12, 14]]])

In [211]:
c[0]

array([[1, 2, 3],
       [5, 6, 7]])

In [212]:
c[0,0]

array([1, 2, 3])

In [213]:
c[0,0,-1]

3

In [214]:
c[:,-1,-2:]

array([[ 6,  7],
       [12, 14]])

**Shaping and Reshaping**

In [215]:
a.shape ## number of columns or number of elements
a



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [216]:
b.shape ### number of rows and columns

(2, 5)

In [217]:


c.shape  ### number od 2-d arrays,rows and columns

(2, 2, 3)

In [218]:
### Reshaping: shape of the array will be changed depending upon the requirement.

### 1-d array to 2-d array:

###2 ,5
###5,2
###10,1
###1,10

print(a)
print(a.ndim)
a1 = a.reshape(2,5)
a2 = a.reshape(5,2)
print(a1)
print(a1.ndim)
print(a2)
print(a2.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


In [219]:
a2 = a.reshape(10,1)
a2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [220]:
### 1-d to 3-d array:

a3 = a.reshape(2,5,1)

In [221]:
a3

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [222]:
a4 = a.reshape(2,1,5)
print(a4)
print(a4.ndim)
print(a4.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]
3
(2, 1, 5)


### Iterating the arrays:



In [223]:
## 1-d array:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [224]:
for i in b:
    print(i,end=" ")

[20 21 22 23 24] [25 26 27 28 29] 

In [225]:
### 2-d array:

for i in b:  ### holds row 
    for j in i: ### holds elements of row
        print(j,end = " ")

20 21 22 23 24 25 26 27 28 29 

In [226]:
for i in c:
    print(i)

[[1 2 3]
 [5 6 7]]
[[ 2  4  6]
 [10 12 14]]


In [227]:
### 3-d array:
for i in c:  ## holds the 2-d array
    for j in i: ###holds the row
        for k in j: ## holds the elements
            print(k,end = " ")

1 2 3 5 6 7 2 4 6 10 12 14 

In [70]:
### nditer():

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 5 6 7 2 4 6 10 12 14 

In [71]:
for i in np.nditer(a):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

### Joining of the arrays:

The shape of the array should be same while performing the concatenation

In [236]:
a
b = np.arange(21,31)
c = np.concatenate((a,b))
print(c)

d = a+b
print(d)
type(d)

[ 1  2  3  4  5  6  7  8  9 10 21 22 23 24 25 26 27 28 29 30]
[22 24 26 28 30 32 34 36 38 40]


numpy.ndarray

In [241]:
c = a.reshape(2,5)
b = b.reshape(2,5)

In [245]:
f = np.concatenate((c,b))
type(f)
f.ndim
f.shape
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### Stastical and Mathematical operations on arrays:

In [249]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [250]:
np.max(c) ### maximum element

10

In [251]:
np.min(c) ## minimum element

1

In [252]:
np.sum(c) ### sum of all the elements

55

In [254]:
c.mean()

5.5

In [255]:
np.average(c)

5.5

In [257]:
np.var(c)

8.25

In [259]:
np.median(c)

5.5

In [260]:
np.std(c)

2.8722813232690143

In [263]:
np.min(c,1)  ### row indicated by 1

array([1, 6])

In [266]:
np.max(c,1) ## column indicated by 0

array([ 5, 10])

In [268]:
np.sum(c,1) ## row wise
np.sum(c,0) ## column wise

array([ 7,  9, 11, 13, 15])

**stacking:** --- arranging the elements
* Horizontal stacking
* Vertical Stacking

In [269]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [270]:
k = np.arange(15,25)
k

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [273]:
np.hstack((a,k))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [274]:
np.vstack((a,k))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [93]:
b 

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [94]:
a = a.reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [95]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 20, 21, 22, 23, 24],
       [ 6,  7,  8,  9, 10, 25, 26, 27, 28, 29]])

In [96]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [97]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481]])

In [98]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [99]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [100]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153]])

In [101]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083]])

In [102]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [103]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [104]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ]])

In [276]:
print(b)
np.remainder(b,6)

[[21 22 23 24 25]
 [26 27 28 29 30]]


array([[3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0]], dtype=int32)

In [106]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
        286.47889757],
       [343.77467708, 401.07045659, 458.3662361 , 515.66201562,
        572.95779513]])

In [278]:
print(b)
np.mod(b,6)

[[21 22 23 24 25]
 [26 27 28 29 30]]


array([[3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0]], dtype=int32)

In [109]:
np.power(b,2)

array([[400, 441, 484, 529, 576],
       [625, 676, 729, 784, 841]], dtype=int32)

In [110]:
np.reciprocal(a)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [111]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [112]:
np.multiply(a,2)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [113]:
np.divide(a,2)

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ]])

In [114]:
np.real(a)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [115]:
np.imag(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [116]:
### Ravel and Flatten:

## ravel : when we create a copy array using ravel function,automatically the changes applied to the copy array will be replicated the original array also
## Flatten :Opposite to ravel
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [117]:
copy_a = a.ravel()
copy_a

array([1, 2, 3, 4, 5])

In [118]:
copy_a[0] = 10

In [119]:
copy_a

array([10,  2,  3,  4,  5])

In [120]:
a

array([10,  2,  3,  4,  5])

In [121]:
### flatten:

a

array([10,  2,  3,  4,  5])

In [122]:
copy_f = a.flatten()
copy_f

array([10,  2,  3,  4,  5])

In [123]:
copy_f[0] = 1
copy_f

array([1, 2, 3, 4, 5])

In [282]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Random methods:

In [299]:
import numpy as np
np.random.randint(1,60) ## single integer element

19

In [307]:
np.random.rand()  ## in the range of 0 and 1 elements will be generated

0.005360905676714989

In [315]:
np.random.randint(50,size=10)

array([ 0, 15, 15, 41, 43,  0, 16, 10, 34, 45])

In [318]:
np.random.randint(20,size = (2,4))

array([[13,  9, 17, 11],
       [ 3,  2, 12, 11]])

In [319]:
np.random.randint(20,size = (4,3,2))

array([[[ 1, 10],
        [ 7, 17],
        [17,  6]],

       [[ 2,  1],
        [ 3,  7],
        [ 8,  7]],

       [[10,  2],
        [ 2,  7],
        [13, 12]],

       [[18, 19],
        [10,  9],
        [ 5,  7]]])

In [328]:
np.random.choice(range(0,30,2),size=4)

array([12,  2, 26,  8])

In [131]:
np.random.choice([1,2,3,4,5],size = (2,5))

array([[5, 5, 1, 5, 4],
       [4, 4, 1, 1, 3]])

In [132]:
np.random.choice([1,2,3,4,5],size = (2,2,2))

array([[[3, 3],
        [2, 4]],

       [[4, 3],
        [3, 3]]])

In [333]:
a = np.arange(1,10)
print(a)
np.random.shuffle(a)

[1 2 3 4 5 6 7 8 9]


In [334]:
a

array([7, 6, 8, 9, 2, 1, 5, 3, 4])

In [135]:
np.random.randn(10)

array([ 1.16888779, -0.07239794, -0.18116188,  0.85629863, -0.12270561,
       -0.97141603, -1.02988144,  0.32257321,  2.35888684, -1.11855842])

In [136]:
np.random.normal()

-0.7930067331608882

In [137]:
np.random.binomial(10,p = [0,1],size = (3,2))

array([[ 0, 10],
       [ 0, 10],
       [ 0, 10]])

In [138]:
np.random.choice([1,2,3,4,5],p = [0.5,0.1,0.2,0.2,0],size = (2,5))

array([[1, 1, 4, 3, 4],
       [1, 4, 1, 1, 3]])

In [139]:
### Array Filtering:

a = np.array([1,2,25,30,40])
c = a > 20

In [140]:
a[c]

array([25, 30, 40])

In [141]:
d = a<20
a[d]

array([1, 2])